language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: otnr3QRj1cDPdvQC09KfbSuws8sVwAyBJYFyC8VP5m2glef04JaeQ2wI1sXA/TLt0pUiZT0yLxG3M07AQBOv3ke4SRgQywbRYuSWHeHPwieRZOUJNdDth/fkU104mS3ir1aWxeABe2EKulF+reaLjYwPmndplxgILD8tCGhf+JWXChZQSpda+P3/EdTs48pfqTMHFus1ycyvcC5pe/Z4KrQwMt3V95bY1yRUI2RcXEjD0/k1MgwtYn16JGlLzZXlt4QtscpCZoWEgSwGIiI0j2Ur9rU5edOU3bV09ji1GOh5UbWefrTOXYO2T9NQLFWHDb2xpWAPYw0SPIWmi4o7UJ6Ol5l2wIP4wecp8SOlSgxd2LZ7ORrsTwnAu8wW7UZMtX2hGgNL1sEGyhZ4X/+Jwm1HqVDhuE8byhMBWR7HVAZw7jA7Qhhr3E5qr29KULbn0vUgfW48FEhgOQD/NtDvfv7sIR7rt5REPPdwPViYc1aHt26Txt183qihW2ZMigp2POP80aHdoyzcHscInr98In7NKFPtRrEnmv4hUBw+VKZhRL0k+JO0gIFwOSVTOR6+V/FWN9tFaF+Yscbe606eXEx+uksV99JK/S3BOfZLWzQH3IVY28mmbrcopRhKj59buiwWG0OsPTNTr/MASPSmulArm8TWpZE45Y54WumBEuA=
  file:
    - "retext-spell.js"
    - "retext-spell.min.js"
  on:
    tags: true
